FROM bitnami/spark:latest

WORKDIR /opt/bitnami/spark

RUN pip install py4j

RUN pwd

COPY ./../src/spark_pgsql/spark_streaming.py ./spark_streaming.py
COPY ./../src/constants.py ./src/constants.py

ENV POSTGRES_DOCKER_USER=host.docker.internal
ARG POSTGRES_PASSWORD
ENV POSTGRES_PASSWORD=$POSTGRES_PASSWORD
